In [74]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [75]:
df=pd.read_csv(r"credit_risk_dataset.csv")

In [76]:
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

In [77]:
df.head()

,Age,Income,Loan_Amount,Credit_Score,Employment_Years,Education_Level,Housing_Status,Default
0,59,52154.0,11276,823,15,Bachelors,Own,0
1,49,116646.0,43663,315,5,PhD,Own,0
2,35,61157.0,18994,428,8,Masters,Own,1
3,63,52154.0,28499,408,26,Bachelors,Rent,0
4,28,148876.0,28040,832,3,Masters,Own,1

In [78]:
df_num=df.select_dtypes(include=['int','float'])

In [79]:
df_num.head()

   Age    Income  Loan_Amount  Credit_Score  Employment_Years  Default
0   59   52154.0        11276           823                15        0
1   49  116646.0        43663           315                 5        0
2   35   61157.0        18994           428                 8        1
3   63   52154.0        28499           408                26        0
4   28  148876.0        28040           832                 3        1

In [80]:
df_num.isnull().sum()

Age                  0
Income              15
Loan_Amount          0
Credit_Score         0
Employment_Years     0
Default              0
dtype: int64

In [81]:
df_cat=df.select_dtypes(include=['object'])

/tmp/ipykernel_193778/2552845908.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df_cat=df.select_dtypes(include=['object'])

In [82]:
df_cat.head()

  Education_Level Housing_Status
0       Bachelors            Own
1             PhD            Own
2         Masters            Own
3       Bachelors           Rent
4         Masters            Own

In [83]:
df_cat.isnull().sum()

Education_Level    0
Housing_Status     0
dtype: int64

In [84]:
for i in df_num:
    df_num[i] = df_num[i].replace(np.nan , df_num[i].median())

In [85]:
df_num.isnull().sum().sum()

np.int64(0)

In [86]:
for i in df_cat:
    print(df_cat[i].value_counts())
    print('-----------------------------------------------------------')

Education_Level
PhD            260
Masters        253
Bachelors      248
High School    239
Name: count, dtype: int64
-----------------------------------------------------------
Housing_Status
Mortgage    349
Own         330
Rent        321
Name: count, dtype: int64
-----------------------------------------------------------

In [87]:
from sklearn.preprocessing import LabelEncoder

In [88]:
le=LabelEncoder()

In [89]:
arr=le.fit_transform(df_cat["Education_Level"])

In [90]:
df_cat['Education_Level']=pd.DataFrame(arr,columns=["Education_Level"])

In [91]:
s=df_cat["Housing_Status"].value_counts()

In [92]:
s

Housing_Status
Mortgage    349
Own         330
Rent        321
Name: count, dtype: int64

In [93]:
df_cat=df_cat["Housing_Status"].map(s)

In [94]:
df_new=pd.concat([df_num,df_cat],axis=1)

In [95]:
df_new.head()

,Age,Income,Loan_Amount,Credit_Score,Employment_Years,Default,Housing_Status
0,59,52154.0,11276,823,15,0,330
1,49,116646.0,43663,315,5,0,330
2,35,61157.0,18994,428,8,1,330
3,63,52154.0,28499,408,26,0,321
4,28,148876.0,28040,832,3,1,330

In [96]:
from sklearn.preprocessing import MinMaxScaler

In [97]:
mms=MinMaxScaler()

In [99]:
mms.fit(df_new)

MinMaxScaler()

In [100]:
df_new.describe().round(3)

,Age,Income,Loan_Amount,Credit_Score,Employment_Years,Default,Housing_Status
count,1000.000,1000.000,1000.000,1000.000,1000.000,1000.000,1000.000
mean,42.515,82210.922,27729.324,581.050,15.164,0.138,333.742
std,12.611,36566.422,12774.836,158.593,8.593,0.345,11.753
min,21.000,20922.000,5097.000,300.000,0.000,0.000,321.000
25%,32.000,52154.000,16387.500,441.000,8.000,0.000,321.000
50%,43.000,79379.000,28483.500,582.000,15.000,0.000,330.000
75%,53.000,116646.000,38535.500,720.250,23.000,0.000,349.000
max,64.000,149038.000,49976.000,849.000,29.000,1.000,349.000

In [101]:
arr=mms.transform(df_new).round(2)
arr

array([[0.88, 0.24, 0.14, ..., 0.52, 0.  , 0.32],
       [0.65, 0.75, 0.86, ..., 0.17, 0.  , 0.32],
       [0.33, 0.31, 0.31, ..., 0.28, 1.  , 0.32],
       ...,
       [0.3 , 0.64, 0.25, ..., 1.  , 0.  , 0.  ],
       [0.91, 0.35, 0.13, ..., 0.83, 0.  , 0.32],
       [0.91, 0.46, 0.06, ..., 0.17, 0.  , 1.  ]], shape=(1000, 7))

In [102]:
for i in df_new:
    df2=pd.DataFrame(arr,columns=[df_new.columns]).round(2)

In [103]:
df2

,Age,Income,Loan_Amount,Credit_Score,Employment_Years,Default,Housing_Status
0,0.88,0.24,0.14,0.95,0.52,0.0,0.32
1,0.65,0.75,0.86,0.03,0.17,0.0,0.32
2,0.33,0.31,0.31,0.23,0.28,1.0,0.32
3,0.98,0.24,0.52,0.20,0.90,0.0,0.00
4,0.16,1.00,0.51,0.97,0.10,1.0,0.32
5,0.47,0.52,0.96,0.49,0.90,0.0,0.32
6,0.88,0.68,0.38,0.29,0.93,0.0,0.32
7,0.42,0.22,0.13,0.47,0.03,1.0,0.32
8,0.51,0.02,0.94,0.18,0.97,0.0,0.32
9,0.23,0.34,0.43,0.92,0.10,1.0,0.32
10,0.23,0.01,0.80,0.45,0.00,1.0,0.00
11,0.53,1.00,0.13,0.98,0.62,0.0,0.32
12,0.81,1.00,0.34,0.24,0.86,0.0,0.32
13,0.91,0.24,0.59,0.64,0.83,0.0,1.00
14,0.53,0.24,0.60,0.36,0.31,0.0,0.00
15,0.05,0.51,0.81,0.69,0.69,0.0,0.00
16,0.49,0.42,0.22,0.41,0.48,0.0,0.00
17,0.02,0.34,0.58,0.87,0.90,0.0,0.00
18,0.53,0.31,0.31,0.87,0.72,0.0,0.32
19,1.00,0.07,0.39,0.48,0.62,1.0,0.32
20,0.67,0.75,0.04,0.68,0.52,0.0,1.00
21,0.86,0.18,0.41,0.88,0.69,0.0,1.00
22,0.02,0.34,0.01,0.79,0.90,0.0,0.00
23,0.47,0.87,0.39,0.38,0.79,0.0,1.00
24,0.74,0.42,0.77,0.68,0.72,0.0,1.00
25,0.26,0.75,0.45,0.72,0.10,0.0,0.00
26,0.49,0.39,0.35,0.82,0.03,1.0,0.00
27,1.00,1.00,0.02,0.66,1.00,0.0,1.00
28,0.56,0.51,0.57,0.83,0.83,0.0,0.32
29,0.60,0.55,0.57,0.41,0.41,0.0,1.00
30,0.95,0.42,0.00,0.24,0.93,1.0,1.00
31,0.63,0.68,0.61,0.87,0.00,0.0,0.32
32,0.35,0.51,0.34,0.50,0.55,0.0,0.32
33,0.33,0.44,0.87,0.28,0.41,0.0,0.00
34,1.00,0.34,0.02,0.40,0.10,0.0,0.00
35,0.05,0.46,0.46,0.34,0.21,0.0,1.00
36,0.84,0.76,0.24,0.76,0.55,0.0,0.32
37,0.14,0.52,0.63,0.99,0.28,1.0,0.00
38,0.47,1.00,0.84,0.07,0.10,0.0,1.00
39,0.19,0.34,0.88,0.56,0.62,0.0,0.32
40,0.88,0.42,0.66,0.61,0.00,0.0,1.00
41,0.40,0.68,0.20,0.57,0.31,0.0,0.00
42,0.07,0.18,0.76,0.13,0.10,0.0,0.00
43,0.56,0.24,0.57,0.51,0.28,0.0,0.32
44,0.30,0.55,0.92,0.32,0.41,0.0,1.00
45,0.19,0.52,0.78,0.50,0.45,0.0,0.32
46,0.58,0.31,0.03,0.52,0.31,0.0,0.00
47,0.02,0.80,0.85,0.49,0.17,0.0,0.00
48,0.44,0.75,0.00,0.12,0.52,0.0,1.00
49,0.63,0.97,0.53,0.88,0.17,0.0,1.00
50,0.14,0.50,0.34,0.45,0.55,0.0,1.00
51,1.00,0.50,0.15,0.28,0.31,1.0,0.32
52,0.16,0.01,0.14,0.08,0.59,0.0,1.00
53,0.79,0.64,0.07,0.83,0.90,0.0,1.00
54,0.30,1.00,0.20,0.36,0.72,1.0,0.00
55,0.37,0.24,0.90,0.22,0.59,1.0,0.00
56,0.81,0.62,0.30,0.00,0.07,0.0,1.00
57,0.91,0.34,0.27,0.35,0.66,0.0,1.00
58,0.07,0.35,0.87,0.94,0.90,0.0,0.00
59,0.02,0.76,0.51,0.80,0.69,0.0,1.00
60,0.12,0.75,0.86,0.26,0.83,0.0,0.32
61,0.95,0.39,0.72,0.35,0.93,0.0,0.32
62,0.07,0.46,0.28,0.97,0.48,0.0,0.32
63,0.65,0.55,0.04,0.41,0.48,0.0,1.00
64,0.40,0.80,0.97,0.57,0.10,0.0,0.00
65,0.58,0.00,0.38,0.55,0.97,0.0,1.00
66,1.00,0.51,0.10,0.84,0.90,0.0,1.00
67,0.77,0.55,0.23,0.73,0.28,0.0,0.00
68,0.21,0.24,0.94,0.71,0.90,0.0,0.00
69,0.81,0.39,0.93,0.38,0.86,0.0,0.00
70,0.30,0.46,0.95,0.38,0.62,0.0,0.32
71,0.70,1.00,0.51,0.21,0.79,1.0,1.00
72,0.33,0.34,0.90,0.46,0.93,0.0,0.00
73,0.16,0.93,0.30,0.40,0.55,0.0,1.00
74,0.30,0.00,0.83,0.74,0.34,1.0,0.32
75,0.51,1.00,0.84,0.81,0.83,0.0,0.32
76,0.91,0.64,0.34,0.64,0.28,0.0,0.00
77,0.47,0.64,0.50,1.00,0.31,1.0,0.00
78,0.35,0.18,0.64,0.26,0.59,0.0,1.00
79,0.40,0.51,0.34,0.91,0.66,0.0,0.00
80,0.53,0.35,0.53,0.99,0.41,0.0,1.00
81,0.58,0.45,0.81,0.99,0.24,0.0,0.00
82,0.56,0.76,0.00,0.92,0.21,0.0,1.00
83,0.93,0.51,0.70,0.51,0.55,0.0,1.00
84,0.65,0.75,1.00,0.77,0.69,0.0,1.00
85,0.33,0.87,0.65,0.49,0.76,0.0,1.00
86,0.00,0.02,0.95,0.28,0.48,0.0,0.32
87,0.56,0.72,0.83,0.15,0.66,0.0,1.00
88,0.14,0.46,0.68,0.77,0.48,0.0,0.00
89,0.19,0.34,0.80,0.50,0.00,0.0,0.32
90,0.53,0.14,0.71,0.52,0.83,0.0,0.32
91,0.00,0.34,0.30,0.31,0.45,0.0,1.00
92,1.00,0.04,0.43,0.59,0.14,0.0,0.32
93,0.16,0.42,0.94,0.11,0.34,0.0,1.00
94,0.53,0.18,0.30,0.13,0.52,1.0,0.00
95,0.23,1.00,0.60,0.68,0.03,0.0,1.00
96,0.37,0.08,0.99,0.92,0.24,0.0,0.32
97,0.16,0.76,0.18,0.72,0.34,0.0,0.00
98,0.79,0.72,0.80,0.22,0.97,1.0,1.00
99,0.79,0.42,0.09,0.79,0.59,0.0,0.00
100,0.74,0.08,0.84,0.85,0.07,0.0,0.00
101,0.09,0.52,0.38,0.52,1.00,0.0,0.32
102,0.95,0.50,0.91,0.48,0.86,0.0,0.00
103,0.88,0.24,0.12,0.58,0.00,0.0,0.32
104,0.93,0.42,0.17,0.68,0.34,0.0,0.00
105,0.63,0.76,0.48,0.16,0.52,1.0,1.00
106,0.14,0.51,0.15,0.37,0.59,0.0,0.00
107,0.19,0.50,0.60,0.61,1.00,0.0,1.00
108,0.16,0.31,0.43,0.40,0.52,1.0,1.00
109,0.26,0.00,0.01,0.07,0.76,0.0,0.00
110,0.77,0.50,0.89,0.12,0.31,0.0,1.00
111,0.74,0.72,0.58,0.93,0.59,0.0,0.00
112,0.51,0.04,0.80,0.23,0.17,0.0,0.00
113,0.53,0.07,0.65,0.46,0.62,0.0,1.00
114,0.84,0.35,0.03,0.03,0.10,0.0,1.00
115,0.79,0.50,0.58,0.87,0.90,0.0,0.32
116,1.00,0.07,0.09,0.11,0.41,0.0,1.00
117,0.91,0.76,0.81,0.79,0.79,0.0,0.32
118,0.49,0.50,0.17,0.49,0.45,0.0,1.00
119,0.60,0.34,0.69,0.06,0.07,0.0,0.00
120,0.79,0.50,0.75,0.90,0.31,0.0,1.00
121,0.00,0.72,0.56,0.85,0.17,0.0,0.00
122,0.79,0.46,0.39,0.59,0.00,0.0,0.00
123,0.84,0.80,0.85,0.55,0.76,1.0,0.00
124,0.30,0.44,0.08,0.50,0.79,0.0,0.32
125,0.05,0.64,0.03,0.36,0.90,0.0,1.00
126,0.00,0.39,0.91,0.81,0.45,0.0,0.00
127,0.09,1.00,0.93,0.59,0.24,0.0,0.00
128,0.58,0.19,0.58,0.06,0.62,0.0,0.32
129,0.30,0.80,0.08,0.88,0.45,0.0,1.00
130,0.88,0.64,0.52,0.87,0.31,0.0,1.00
131,0.60,0.24,0.62,0.12,0.55,0.0,0.32
132,0.19,0.50,0.84,0.01,0.28,0.0,0.32
133,0.33,0.22,0.78,0.55,0.97,0.0,1.00
134,0.33,0.24,0.20,0.62,0.17,0.0,0.32
135,0.58,0.64,0.27,0.78,0.34,0.0,1.00
136,0.95,0.55,0.79,0.77,0.83,0.0,1.00
137,0.28,0.34,0.70,0.60,0.21,0.0,0.00
138,0.72,0.19,0.85,0.80,0.55,0.0,0.00
139,0.88,0.46,0.39,0.32,0.93,0.0,1.00
140,0.72,0.46,0.20,0.96,0.93,0.0,1.00
141,0.07,0.62,0.62,0.05,0.00,0.0,1.00
142,0.67,1.00,0.69,0.74,0.72,0.0,1.00
143,0.84,1.00,0.50,0.42,0.14,0.0,1.00
144,0.51,0.31,0.32,0.97,0.28,0.0,1.00
145,0.88,0.02,0.98,1.00,0.59,1.0,0.32
146,0.33,0.50,0.88,0.92,0.79,0.0,1.00
147,0.98,0.50,0.25,0.32,0.90,0.0,0.32
148,0.65,0.31,0.57,0.24,0.69,0.0,0.32
149,0.81,0.64,0.79,0.83,0.03,0.0,1.00
150,0.28,0.87,0.27,0.63,0.97,1.0,1.00
151,0.72,1.00,0.93,0.98,0.86,0.0,0.32
152,0.14,0.52,0.50,0.74,0.34,0.0,0.32
153,0.49,0.46,0.63,0.14,0.90,0.0,1.00
154,0.63,0.75,0.14,0.89,0.93,0.0,1.00
155,0.02,0.24,0.79,0.35,0.17,0.0,0.32
156,0.95,0.90,0.97,0.29,0.86,0.0,0.32
157,0.12,0.08,0.59,0.63,0.24,0.0,0.32
158,0.63,0.80,0.70,0.66,0.10,0.0,0.00
159,0.63,0.18,0.02,0.16,0.59,0.0,0.32
160,1.00,0.18,0.10,0.48,0.93,1.0,0.00
161,1.00,0.19,0.73,0.39,0.34,0.0,1.00
162,0.44,0.55,0.48,0.48,0.14,0.0,1.00
163,0.67,0.14,0.36,0.51,0.48,0.0,0.32
164,0.23,0.52,0.26,0.85,0.93,0.0,1.00
165,0.63,0.39,0.61,0.69,0.59,0.0,1.00
166,0.56,0.50,0.26,0.66,0.03,0.0,1.00
167,0.88,0.80,0.97,0.82,0.72,0.0,1.00
168,0.74,0.31,0.18,0.80,0.34,1.0,0.00
169,0.00,0.72,0.57,0.17,0.86,0.0,0.00
170,0.60,0.24,0.60,0.77,0.83,0.0,0.32
171,0.28,0.75,0.36,0.26,0.41,0.0,0.32
172,0.93,0.46,0.60,0.53,0.10,0.0,0.32
173,0.05,0.08,0.29,0.79,0.72,0.0,1.00
174,0.88,0.08,0.87,0.09,0.21,0.0,1.00
175,0.12,0.39,0.55,0.55,0.97,0.0,0.00
176,0.16,0.75,0.74,0.34,0.34,1.0,0.00
177,0.60,1.00,0.93,0.25,0.72,0.0,0.32
178,0.19,0.80,0.10,0.73,0.79,0.0,0.00
179,0.84,0.08,0.62,0.62,0.10,0.0,0.00
180,0.74,1.00,0.48,0.58,0.93,0.0,0.00
181,0.95,0.52,0.87,0.66,0.48,0.0,0.00
182,1.00,0.50,0.20,0.69,0.00,0.0,0.00
183,0.53,1.00,0.82,0.42,0.76,0.0,0.32
184,0.33,0.75,1.00,0.62,0.07,0.0,0.32
185,0.72,0.14,0.29,1.00,0.45,0.0,0.00
186,0.72,0.45,0.84,0.96,0.17,0.0,0.32
187,0.53,0.80,0.13,0.33,0.59,0.0,1.00
188,0.93,0.08,0.16,0.07,0.83,0.0,0.00
189,0.26,0.62,0.63,0.72,0.00,0.0,1.00
190,0.88,0.80,0.60,0.90,0.17,0.0,0.32
191,0.02,0.55,0.81,0.60,0.17,0.0,0.32
192,0.05,0.42,0.95,0.23,0.69,0.0,1.00
193,0.84,0.55,0.15,0.00,0.52,0.0,0.32
194,0.37,0.52,0.30,0.30,0.97,0.0,0.00
195,0.02,0.80,0.69,0.03,0.14,0.0,1.00
196,0.02,0.00,0.95,0.60,0.55,0.0,0.00
197,0.63,0.62,0.27,0.83,0.31,0.0,1.00
198,0.51,0.01,1.00,0.20,0.93,0.0,0.32
199,0.84,0.55,0.97,0.49,0.69,0.0,1.00
200,0.72,0.46,0.51,0.81,0.59,0.0,1.00
201,0.74,0.72,0.78,0.44,0.21,0.0,0.00
202,0.00,0.18,0.46,0.55,0.07,0.0,0.32
203,0.42,0.72,0.76,0.19,0.41,0.0,0.00
204,0.02,0.52,0.98,0.45,0.48,1.0,0.32
205,1.00,0.39,0.66,0.82,0.66,0.0,0.00
206,0.58,0.00,0.15,0.95,0.62,0.0,1.00
207,0.72,0.19,0.08,0.28,0.07,0.0,0.00
208,0.12,0.55,0.52,0.32,0.10,0.0,0.32
209,0.72,0.19,0.42,0.62,0.14,0.0,0.32
210,0.07,0.24,0.54,0.78,0.00,0.0,1.00
211,0.23,0.24,0.19,0.59,0.10,0.0,0.32
212,0.37,0.46,0.14,0.76,0.38,0.0,0.00
213,0.86,0.02,0.55,0.88,0.93,0.0,1.00
214,0.53,0.46,0.94,0.75,0.90,0.0,0.32
215,0.09,1.00,0.27,0.15,0.79,0.0,0.32
216,0.77,0.31,0.77,0.20,0.31,0.0,0.00
217,0.12,0.07,0.94,0.60,0.76,0.0,0.00
218,0.49,0.75,0.48,0.69,0.83,1.0,1.00
219,0.23,0.97,0.12,0.07,0.69,1.0,0.32
220,0.35,0.02,0.95,0.19,0.97,0.0,0.00
221,0.74,0.08,0.30,0.37,0.86,0.0,1.00
222,0.19,0.39,0.25,0.82,0.66,1.0,0.32
223,0.12,0.68,0.50,0.48,0.79,0.0,0.32
224,0.35,0.07,0.34,0.38,0.83,0.0,1.00
225,0.65,0.31,0.53,0.21,0.41,1.0,1.00
226,0.05,0.80,0.76,0.68,0.76,0.0,0.00
227,0.44,0.87,0.52,0.98,0.45,0.0,0.32
228,0.81,0.64,0.21,0.15,0.76,0.0,0.32
229,0.42,0.64,0.63,0.83,0.14,0.0,0.32
230,0.58,0.14,0.83,0.93,0.10,0.0,1.00
231,0.05,0.18,0.36,0.70,0.45,0.0,0.00
232,0.42,0.45,0.23,0.64,0.31,0.0,0.32
233,0.44,0.76,0.86,0.54,0.55,0.0,1.00
234,0.72,0.18,0.22,0.47,0.31,0.0,0.32
235,0.14,0.08,0.70,0.15,0.86,0.0,0.00
236,0.93,0.04,0.14,0.49,0.21,0.0,0.32
237,0.74,0.18,0.80,0.76,0.52,1.0,0.00
238,0.91,0.64,0.76,0.43,0.00,0.0,0.00
239,0.88,0.55,0.88,0.56,0.55,0.0,0.32
240,0.40,0.39,0.81,0.65,0.69,0.0,0.32
241,0.91,0.80,0.16,0.39,0.97,0.0,0.00
242,0.00,0.04,0.71,0.09,0.28,0.0,1.00
243,0.23,0.31,0.80,0.23,0.17,0.0,0.00
244,0.63,1.00,0.52,0.40,0.62,0.0,0.32
245,0.56,0.04,0.00,0.51,0.41,0.0,0.32
246,0.51,0.62,0.84,0.74,0.07,0.0,1.00
247,0.70,0.64,0.36,0.92,0.21,0.0,0.00
248,0.67,0.34,0.07,0.53,0.72,0.0,0.00
249,0.95,0.02,0.94,0.50,0.28,0.0,0.00
250,0.79,0.22,0.58,0.80,0.72,0.0,0.32
251,0.14,0.76,0.39,0.19,0.14,0.0,0.00
252,0.35,0.90,0.65,0.76,0.31,1.0,1.00
253,0.58,0.64,0.38,0.78,0.76,0.0,0.32
254,0.02,0.76,0.33,0.68,0.55,0.0,0.32
255,0.00,0.42,0.93,0.13,0.38,0.0,0.00
256,0.26,0.55,0.26,0.05,0.76,0.0,1.00
257,0.09,0.52,0.06,0.34,0.52,0.0,0.32
258,0.84,0.51,0.35,0.66,0.07,0.0,0.32
259,0.72,0.24,0.60,0.82,1.00,0.0,0.00
260,0.19,0.22,0.75,0.35,0.83,0.0,0.00
261,0.93,0.14,0.90,0.28,0.72,0.0,1.00
262,0.79,0.39,0.53,0.31,0.28,0.0,0.00
263,0.42,0.80,0.58,0.07,0.97,0.0,1.00
264,0.35,0.75,0.20,0.11,0.48,0.0,0.32
265,0.05,0.42,0.60,0.04,0.14,0.0,1.00
266,0.44,0.46,0.88,0.65,0.76,0.0,1.00
267,0.53,0.00,0.16,0.13,0.41,0.0,1.00
268,0.74,0.97,0.47,0.21,0.45,0.0,0.32
269,0.53,0.24,0.75,0.69,0.66,1.0,0.00
270,0.23,0.35,0.39,0.53,0.48,0.0,0.32
271,0.16,0.87,0.09,0.80,0.52,0.0,0.00
272,0.81,0.14,0.63,0.01,0.76,0.0,1.00
273,0.86,0.04,0.71,0.36,0.41,0.0,1.00
274,0.91,0.80,0.51,0.77,0.55,0.0,1.00
275,0.44,0.76,0.71,0.35,0.76,0.0,1.00
276,0.79,0.87,0.72,0.27,0.24,0.0,1.00
277,0.56,0.68,0.99,0.37,0.69,0.0,0.00
278,0.79,0.39,0.65,0.81,0.03,0.0,0.00
279,0.56,0.97,0.85,0.76,0.14,0.0,1.00
280,0.65,0.76,0.39,0.78,0.17,0.0,0.32
281,0.40,0.00,0.75,0.87,0.38,0.0,0.32
282,0.40,0.34,0.24,0.86,0.59,0.0,1.00
283,0.02,0.01,0.69,0.23,1.00,0.0,0.00
284,0.79,0.42,0.57,0.72,0.72,0.0,0.32
285,0.35,0.34,0.88,0.59,0.72,0.0,0.32
286,0.93,0.34,0.27,0.71,0.00,0.0,0.32
287,0.81,0.14,0.17,0.80,1.00,0.0,1.00
288,0.74,0.68,0.31,0.37,0.55,1.0,0.32
289,0.07,0.22,0.36,0.88,1.00,0.0,0.32
290,0.74,0.72,0.70,0.05,0.34,0.0,0.32
291,0.30,0.18,0.22,0.70,0.31,0.0,0.32
292,0.47,0.22,0.84,0.79,0.62,0.0,0.00
293,0.44,0.04,0.05,0.68,0.45,1.0,1.00
294,0.16,0.51,0.15,0.62,0.86,0.0,1.00
295,0.14,0.00,0.08,0.81,0.31,0.0,0.00
296,0.05,0.50,0.11,0.13,0.48,0.0,0.00
297,0.37,0.55,0.24,0.28,0.93,0.0,1.00
298,0.74,0.02,0.05,0.78,0.62,1.0,0.32
299,0.26,0.42,0.81,0.66,0.10,0.0,0.32
300,0.49,0.46,0.09,0.81,0.03,1.0,1.00
301,0.49,1.00,0.32,0.42,0.28,0.0,0.32
302,0.67,0.24,0.77,0.48,0.31,0.0,0.00
303,0.86,1.00,0.18,0.23,0.93,0.0,0.32
304,0.86,0.51,0.91,0.44,0.34,0.0,0.32
305,0.16,0.24,0.78,0.99,0.45,0.0,0.32
306,0.60,0.00,0.89,0.88,0.21,0.0,1.00
307,0.60,0.75,0.19,0.22,0.76,0.0,0.00
308,0.77,0.34,0.72,0.23,0.48,0.0,0.32
309,0.47,0.75,0.11,1.00,0.72,0.0,1.00
310,0.67,0.24,0.43,0.31,0.62,0.0,0.32
311,0.74,0.50,0.21,0.22,0.72,0.0,0.00
312,0.63,0.90,0.71,0.06,0.48,0.0,0.32
313,0.74,0.34,0.01,0.16,1.00,0.0,0.00
314,0.09,0.45,1.00,0.36,0.93,0.0,0.32
315,0.42,0.14,0.67,0.67,0.79,0.0,0.00
316,0.07,1.00,0.95,0.14,0.24,0.0,0.32
317,0.79,0.08,0.23,0.11,0.34,0.0,0.00
318,0.37,0.76,0.07,0.78,0.97,0.0,0.32
319,1.00,0.31,0.57,0.91,0.28,0.0,0.32
320,0.63,0.52,0.64,0.20,0.48,1.0,1.00
321,0.67,0.24,0.00,0.50,0.00,0.0,1.00
322,0.65,1.00,0.79,0.12,1.00,0.0,0.00
323,0.12,0.07,0.51,0.12,0.00,0.0,0.32
324,0.79,0.19,0.74,0.30,0.62,0.0,0.00
325,0.93,0.45,0.07,0.89,0.07,0.0,1.00
326,0.84,0.42,0.65,0.55,0.31,0.0,0.00
327,0.53,0.04,0.95,0.66,0.24,0.0,0.00
328,0.65,0.22,0.45,0.69,0.48,1.0,1.00
329,0.70,0.42,0.89,0.62,0.31,0.0,0.32
330,0.79,0.14,0.24,0.64,0.00,0.0,0.00
331,0.74,0.64,0.77,0.76,0.97,0.0,1.00
332,0.47,0.51,0.35,0.20,0.59,0.0,0.32
333,0.72,0.02,0.73,0.90,0.03,1.0,1.00
334,0.51,0.64,0.16,0.62,0.62,0.0,0.00
335,0.74,0.64,0.83,0.70,0.41,0.0,0.32
336,0.05,0.34,0.65,0.97,0.72,0.0,0.32
337,0.40,0.04,0.58,0.54,0.00,0.0,1.00
338,0.56,0.46,0.92,0.25,0.03,1.0,1.00
339,0.95,0.76,0.42,0.65,0.97,0.0,1.00
340,0.70,0.42,0.72,0.91,0.52,0.0,0.32
341,0.05,0.34,0.37,0.70,0.48,1.0,0.32
342,0.91,0.97,0.73,0.51,0.41,1.0,0.00
343,0.53,0.76,0.30,0.88,0.52,0.0,0.32
344,0.72,0.90,0.45,0.20,0.55,0.0,0.00
345,0.49,0.45,0.58,0.25,0.69,0.0,1.00
346,0.51,0.08,0.11,0.79,0.97,0.0,1.00
347,0.02,0.31,0.24,0.93,0.97,0.0,0.32
348,0.60,0.80,0.24,0.50,0.21,0.0,1.00
349,0.95,0.18,0.21,0.18,0.79,0.0,1.00
350,0.02,0.18,0.42,0.19,0.86,0.0,0.32
351,0.58,1.00,0.36,0.39,0.55,0.0,0.00
352,0.37,0.64,0.13,0.30,0.21,0.0,0.32
353,0.91,0.87,0.50,0.95,0.41,0.0,0.00
354,0.74,0.14,0.42,0.52,0.14,0.0,0.32
355,0.19,0.68,0.79,0.94,0.86,0.0,0.32
356,0.98,0.19,0.68,0.30,0.55,0.0,1.00
357,0.88,0.80,0.42,0.11,0.07,0.0,0.32
358,0.65,0.18,0.85,0.16,0.21,0.0,0.32
359,0.95,0.50,0.95,0.21,0.86,0.0,0.00
360,0.58,0.04,0.40,0.48,0.55,0.0,1.00
361,0.79,0.18,0.80,0.25,0.21,0.0,0.00
362,0.56,0.50,0.83,0.45,0.69,0.0,0.00
363,0.53,1.00,0.55,0.72,0.00,0.0,1.00
364,0.28,0.68,0.40,0.89,0.55,0.0,1.00
365,0.14,0.55,0.55,0.87,1.00,1.0,1.00
366,0.81,0.08,0.23,0.94,0.55,0.0,0.32
367,0.44,0.19,0.10,0.33,0.34,0.0,1.00
368,0.00,0.75,0.12,0.03,0.83,1.0,1.00
369,0.16,0.01,0.55,0.95,0.90,0.0,1.00
370,0.35,0.00,0.82,0.96,0.97,0.0,0.00
371,0.30,0.04,0.71,0.27,0.07,0.0,0.00
372,0.26,0.39,0.74,0.55,0.48,1.0,0.32
373,0.51,0.80,0.27,0.41,0.97,0.0,0.00
374,0.33,0.55,0.56,0.18,0.69,0.0,0.32
375,0.63,0.42,0.49,0.76,0.34,0.0,0.00
376,0.77,0.75,0.77,0.39,0.86,0.0,1.00
377,0.02,0.76,0.25,0.74,0.93,0.0,0.00
378,0.72,0.46,0.17,0.72,0.52,0.0,0.32
379,0.51,0.76,0.18,0.91,0.83,0.0,0.00
380,0.49,0.68,0.63,0.85,0.72,0.0,1.00
381,0.56,0.93,0.71,0.15,0.93,0.0,0.32
382,0.49,0.51,0.66,0.66,0.28,0.0,1.00
383,0.49,0.35,0.90,0.30,0.79,0.0,1.00
384,0.95,0.22,0.18,0.09,0.79,0.0,0.32
385,0.12,0.51,0.28,0.93,0.00,0.0,1.00
386,0.33,1.00,0.54,0.60,0.97,0.0,1.00
387,0.98,0.80,0.15,0.21,0.83,0.0,0.00
388,0.84,0.18,0.46,0.61,0.72,0.0,1.00
389,0.74,0.55,0.16,0.27,0.52,0.0,1.00
390,0.16,0.72,0.86,0.59,0.28,0.0,1.00
391,1.00,0.04,0.64,0.81,0.62,0.0,1.00
392,1.00,0.39,0.12,0.02,0.38,0.0,0.32
393,0.09,0.51,0.20,0.90,0.62,1.0,0.00
394,0.88,0.00,0.67,0.52,0.72,1.0,1.00
395,0.07,0.76,0.18,0.21,0.28,0.0,1.00
396,0.12,0.72,0.13,0.87,0.21,0.0,0.32
397,0.72,0.62,0.70,0.04,0.45,0.0,1.00
398,0.67,0.93,0.57,0.63,0.97,0.0,0.32
399,0.79,0.72,0.69,0.58,0.62,0.0,0.00
400,0.91,0.64,0.84,0.23,0.62,1.0,0.00
401,0.35,1.00,0.19,0.50,0.03,0.0,1.00
402,0.28,0.55,0.33,0.37,0.28,1.0,1.00
403,0.95,0.75,0.25,0.35,0.41,0.0,1.00
404,0.67,0.31,0.78,0.99,0.48,0.0,0.32
405,0.42,0.39,0.52,0.52,0.07,0.0,1.00
406,0.37,0.24,0.13,0.10,0.34,0.0,1.00
407,0.42,0.46,0.79,0.55,0.69,0.0,0.00
408,0.63,0.01,0.89,0.30,0.45,0.0,1.00
409,0.58,0.64,0.38,0.03,1.00,0.0,0.00
410,0.84,0.90,0.37,0.67,0.83,0.0,1.00
411,0.58,0.45,0.71,0.48,0.24,0.0,0.00
412,0.51,0.46,0.89,0.20,0.59,0.0,1.00
413,0.19,0.97,0.52,0.89,0.62,0.0,0.00
414,0.26,0.90,0.18,0.59,0.52,0.0,0.32
415,0.00,0.04,0.26,0.99,0.03,1.0,0.00
416,0.00,0.62,0.64,0.12,0.24,0.0,0.00
417,0.77,0.01,0.26,0.53,0.72,0.0,0.00
418,0.72,0.08,0.19,0.04,0.17,0.0,1.00
419,0.56,0.45,0.75,1.00,0.38,0.0,1.00
420,0.91,0.18,0.63,0.00,0.48,0.0,1.00
421,0.00,0.22,0.78,1.00,0.83,0.0,0.32
422,0.35,0.14,0.28,0.26,0.24,0.0,0.32
423,0.88,0.08,0.40,0.34,0.10,0.0,0.00
424,0.09,0.80,0.27,0.23,0.48,0.0,0.32
425,0.49,0.42,0.46,0.36,0.93,1.0,0.00
426,0.65,0.34,0.84,0.23,0.66,1.0,0.00
427,0.05,0.51,0.61,0.47,0.83,0.0,0.00
428,0.26,0.39,0.15,0.99,0.55,0.0,0.32
429,0.58,0.18,0.14,0.35,0.41,0.0,1.00
430,0.35,0.90,0.89,0.19,0.59,0.0,0.32
431,0.84,0.93,0.31,0.97,0.03,0.0,0.00
432,0.49,0.50,0.95,0.48,0.41,0.0,0.00
433,0.65,0.52,0.70,0.70,0.41,1.0,0.32
434,0.30,0.24,0.87,0.47,0.72,1.0,0.00
435,0.63,0.76,0.81,0.75,0.48,0.0,0.00
436,0.09,0.76,0.59,0.65,0.66,0.0,0.32
437,0.67,0.44,0.67,0.13,0.97,0.0,0.32
438,0.09,0.46,0.56,0.64,0.90,0.0,0.32
439,0.26,0.52,0.84,0.34,0.31,0.0,0.00
440,0.35,0.55,1.00,0.53,0.97,0.0,0.00
441,0.58,0.22,0.66,0.08,0.07,1.0,1.00
442,0.58,0.97,0.12,0.15,0.62,0.0,1.00
443,0.47,0.18,0.64,0.22,0.07,0.0,0.32
444,0.88,0.02,0.62,0.65,0.72,0.0,1.00
445,0.81,0.45,0.20,0.96,0.45,0.0,0.00
446,0.74,0.97,0.14,0.12,0.24,0.0,1.00
447,0.67,0.14,0.71,0.68,0.90,0.0,0.00
448,0.84,0.64,0.52,0.29,0.76,0.0,0.32
449,0.51,0.44,0.92,0.69,1.00,0.0,0.32
450,0.21,0.44,0.71,0.65,0.10,0.0,0.00
451,0.09,0.46,0.76,0.34,0.90,1.0,1.00
452,0.81,0.80,0.52,0.58,0.93,0.0,0.32
453,0.77,0.80,0.96,0.82,0.66,0.0,0.32
454,0.70,0.45,0.03,0.86,0.34,0.0,1.00
455,0.21,0.90,0.76,0.02,0.86,0.0,1.00
456,0.42,0.55,0.93,0.33,0.34,0.0,0.00
457,0.72,0.24,0.07,0.20,0.90,1.0,1.00
458,0.00,0.50,0.93,0.92,1.00,1.0,1.00
459,0.09,0.24,0.74,0.53,0.34,0.0,1.00
460,0.07,0.18,0.27,0.54,0.03,0.0,0.00
461,0.35,0.55,0.83,0.82,1.00,0.0,0.00
462,0.53,0.18,0.34,0.39,0.55,0.0,0.32
463,0.35,1.00,0.94,0.05,0.28,0.0,0.00
464,0.02,0.18,0.72,0.42,0.93,0.0,0.32
465,0.63,0.64,0.12,0.58,0.93,0.0,1.00
466,0.72,0.76,0.75,0.42,0.03,0.0,0.32
467,0.60,0.90,0.33,0.79,0.97,0.0,0.32
468,0.44,0.07,0.69,0.97,0.79,1.0,1.00
469,0.53,0.31,0.69,0.73,0.48,0.0,0.32
470,0.26,0.46,0.59,0.09,0.52,0.0,0.00
471,0.79,0.64,0.61,0.57,0.83,0.0,0.00
472,0.74,0.50,0.76,0.51,0.10,0.0,0.00
473,0.74,0.08,0.69,0.05,0.24,0.0,0.00
474,0.98,0.22,0.22,0.61,0.28,0.0,0.32
475,0.84,0.62,0.86,0.33,0.86,1.0,0.32
476,0.26,0.64,0.24,0.04,0.86,0.0,1.00
477,0.05,0.31,0.08,0.99,0.14,0.0,0.32
478,0.00,0.52,0.10,0.81,0.52,0.0,0.32
479,0.74,0.46,0.54,0.13,0.41,0.0,0.32
480,0.91,0.80,0.14,0.02,1.00,0.0,1.00
481,0.21,0.76,0.84,0.88,0.21,1.0,0.00
482,0.98,0.55,0.17,0.83,0.86,0.0,0.32
483,1.00,0.46,0.97,0.29,0.66,0.0,1.00
484,0.65,0.55,0.51,0.02,0.55,0.0,1.00
485,0.28,0.93,0.53,0.32,0.07,0.0,1.00
486,0.26,0.64,0.91,0.75,0.14,1.0,0.00
487,0.70,0.93,0.12,0.09,0.62,1.0,0.32
488,0.02,0.50,0.57,0.74,0.38,0.0,1.00
489,0.79,0.08,0.68,0.04,0.97,0.0,0.00
490,0.51,0.52,0.50,0.05,0.90,0.0,1.00
491,0.37,0.68,0.55,0.47,0.21,0.0,1.00
492,0.58,0.80,0.36,0.37,0.93,1.0,1.00
493,0.16,0.80,0.78,0.11,0.28,0.0,1.00
494,0.65,0.42,0.01,0.86,0.93,0.0,1.00
495,0.58,0.42,0.00,0.85,0.17,0.0,0.00
496,0.21,0.90,0.92,0.02,0.97,0.0,0.32
497,0.58,0.55,0.98,0.53,0.86,0.0,0.32
498,0.77,0.08,0.10,0.64,0.55,0.0,0.32
499,0.93,0.75,0.23,0.13,0.52,0.0,0.32
500,0.14,0.44,0.10,0.80,0.76,0.0,0.00
501,0.07,0.14,0.50,0.44,0.07,0.0,0.00
502,0.23,0.76,0.65,0.28,0.69,0.0,0.00
503,0.65,0.72,0.54,0.17,0.86,0.0,1.00
504,0.81,0.52,0.24,0.53,0.10,0.0,1.00
505,0.56,0.75,0.86,0.38,0.31,0.0,1.00
506,0.47,0.07,0.56,0.62,0.14,1.0,0.32
507,0.81,0.24,0.83,0.16,0.69,0.0,1.00
508,0.21,1.00,0.63,0.71,0.72,0.0,0.32
509,0.84,0.22,0.74,0.59,1.00,0.0,1.00
510,0.19,0.55,0.47,0.28,0.31,0.0,0.32
511,0.53,0.18,0.16,0.25,0.38,0.0,1.00
512,0.79,0.42,0.31,0.78,0.31,0.0,1.00
513,0.79,0.14,0.63,0.82,0.97,0.0,0.00
514,0.81,0.51,0.58,0.26,0.41,0.0,1.00
515,0.40,0.35,0.68,0.15,0.34,0.0,1.00
516,0.88,0.50,0.44,0.32,0.72,0.0,0.00
517,0.72,0.08,0.96,0.36,0.52,0.0,0.32
518,0.53,0.42,0.69,0.77,0.24,0.0,0.00
519,0.51,0.31,0.73,0.73,0.24,0.0,0.00
520,0.72,0.31,0.07,0.86,0.90,0.0,0.32
521,0.84,1.00,0.74,0.40,0.83,0.0,1.00
522,0.26,0.39,0.55,0.32,0.24,1.0,0.32
523,0.28,0.50,0.87,0.04,0.41,0.0,1.00
524,0.51,0.64,0.08,0.43,0.90,0.0,1.00
525,0.56,0.45,0.14,0.02,0.03,0.0,0.32
526,0.79,0.07,0.94,0.18,1.00,0.0,0.00

In [104]:
from sklearn.model_selection import train_test_split

In [105]:
y=df2['Default']
y.value_counts()

(Default,)
0.0           862
1.0           138
Name: count, dtype: int64

In [124]:
y.head()

  Default
0     0.0
1     0.0
2     1.0
3     0.0
4     1.0

In [125]:
X=df2.drop(columns=['Default'])

/tmp/ipykernel_193778/2030845764.py:1: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  X=df2.drop(columns=['Default'])

In [126]:
X.head()

    Age Income Loan_Amount Credit_Score Employment_Years Housing_Status
0  0.88   0.24        0.14         0.95             0.52           0.32
1  0.65   0.75        0.86         0.03             0.17           0.32
2  0.33   0.31        0.31         0.23             0.28           0.32
3  0.98   0.24        0.52         0.20             0.90           0.00
4  0.16   1.00        0.51         0.97             0.10           0.32

In [127]:
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=.2 , stratify = y , random_state = 12)

In [128]:
X_train.shape

(800, 6)

In [129]:
y_train.shape
y_train = y_train.astype(int)

In [130]:
from sklearn.linear_model import LogisticRegression

In [131]:
lr=LogisticRegression()

In [132]:
lr.fit(X_train, y_train)

/home/gv/Desktop/prac/.venv/lib/python3.13/site-packages/sklearn/utils/validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression()

In [133]:
lr.score(X_train,y_train)

0.8625

In [134]:
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix, classification_report

In [135]:
y_pred=lr.predict(X_test)

In [136]:
print('P_score', precision_score(y_test, y_pred))

P_score 0.0

/home/gv/Desktop/prac/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [137]:
macro_precision = precision_score(y_test, y_pred, average='macro', zero_division=0)

In [138]:
macro_precision

0.43

In [139]:
print('R_score', recall_score(y_test, y_pred))

R_score 0.0

In [140]:
print(confusion_matrix(y_test, y_pred))

[[172   0]
 [ 28   0]]

In [141]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.86      1.00      0.92       172
         1.0       0.00      0.00      0.00        28

    accuracy                           0.86       200
   macro avg       0.43      0.50      0.46       200
weighted avg       0.74      0.86      0.80       200

/home/gv/Desktop/prac/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/gv/Desktop/prac/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/gv/Desktop/prac/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])